name = "CirculantMatrices"
uuid = "ff7ea436-cd3a-11e8-3d20-01065dd5f7ca"
authors = ["Simon B. Adrian <simon.adrian@ieee.org>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
